micronaut:
  application:
    name: pixKeyManager

# http clients
itauerp.client.url: ${ITAUERP_CLIENT_URL:`http://localhost:9091/api`}

# database
datasources:
  default:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/pix?createDatabaseIfNotExist=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD:1234}
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.show_sql: true