micronaut:
  server.port: 8089
  application:
    name: pixKeyManager
  http:
    client:
      read-timeout: 5s

# database
datasources:
  default:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/pix?createDatabaseIfNotExist=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD:1234}
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: 'create-drop'
      hibernate.show_sql: true

# http clients
itauerp.client.url: ${ITAUERP_CLIENT_URL:`http://localhost:9091/api`}
bcb.client.url: ${BCB_CLIENT_URL:`http://localhost:8082/api`}

grpc:
  server:
    health:
      enabled: true

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS