micronaut:
  server.port: 8089
  application:
    name: pixKeyManager
  http:
    client:
      read-timeout: 5s

# database
datasources:
  default:
    url: ${DB_URI:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:q1w2e3}
    schema-generate: CREATE_DROP
    dialect: ${DB_DIALECT:POSTGRES}
jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: 'create-drop'
      hibernate.show_sql: true

# http clients
itauerp.client.url: ${ITAU_URL:`http://localhost:9091/api`}
bcb.client.url: ${BCB_URL:`http://localhost:8082/api`}

grpc:
  server:
    health:
      enabled: true

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS